#!/usr/bin/env bash
set -eou pipefail

url="${1:?url parameter required}"
action="${2:?action parameter required}"

# ignore unsupported actions without error
if [[ "${action}" != "get" ]]; then
    exit 0
fi

plugin_root="$(cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd)"

# read credential helper input from stdin
args="$(< /dev/stdin)"

TIMEFORMAT='[oidc = %2Rs]'
time {
    oidc_auth_token="$(cd "${plugin_root}" && direnv exec . dist/oidc)"
}

# request a token for the given repository from the remote server, using the
# OIDC JWT from the agent.
TIMEFORMAT='[token vendor = %2Rs]'
time curl --silent --show-error --fail \
    --request POST "${url}" \
    --data "${args}" \
    --header "Authorization: Bearer ${oidc_auth_token}" \
    --header "Content-Type: text/plain" \
    --header "Accept: text/plain"
