#!/usr/bin/bash
set -eou pipefail

url="${1:?url parameter required}"
action="${2:?action parameter required}"

# ignore unsupported actions without error
if [[ "${action}" != "get" ]]; then
    exit 0
fi

# read credential helper input from stdin
args="$(< /dev/stdin)"

oidc_auth_token="$(cd /home/jtelfer/src/bkauth && direnv exec . go run cmd/create/main.go)"

# request a token for the given repository from the remote server, using the
# OIDC JWT from the agent.
curl --silent --show-error --fail \
    --request POST "${url}" \
    --data "${args}" \
    --header "Authorization: Bearer ${oidc_auth_token}" \
    --header "Content-Type: text/plain" \
    --header "Accept: text/plain" | tee /dev/stderr
