#!/usr/bin/env bash

#
# executing this script from your infrastructure's environment agent hook will
# configure Github App Auth for every build
#
# Changing the parameters supplied will be necessary to ensure that agents can
# connect to the service and include the correct audience.
#
BUILDKITE_PLUGIN_GITHUB_APP_AUTH_VENDOR_URL="http://vendor" \
BUILDKITE_PLUGIN_GITHUB_APP_AUTH_AUDIENCE="github-app-auth:jamestelfer" \
    source /buildkite/plugins/github-app-auth-buildkite-plugin/hooks/environment

# optional: it is possible to change the git URL, converting it from SSH to
# HTTPS if that is desired.
